spring:
  devtools:
    add-properties: false
logging:
  level:
    web: WARN

secret-sharing:
  asymmetricAlgorithm: RSA
  hashAlgorithm: SHA256withRSA
  keyPairBitSize: 2048
  bitSize: 2048
  maxShares: 60